# Liquibase configuration
spring.liquibase.change-log=classpath:db/changelog/db.integration-test-changelog.yaml

# Optionally, enable logging for Liquibase to debug issues
# logging.level.liquibase=DEBUG